### ISSUE TITLE
Logo 更新

### ISSUE THREAD

**Issue by yuaanlin** [yuaanlin/nextjs.tw#11]
昨天晚上 Next.js 官方推出了新的 Logo，因此我們的網站需要更新

<img width="1709" alt="Screen Shot 2022-09-03 at 2 13 44 PM" src="https://user-images.githubusercontent.com/21105863/188258400-4fc030ca-5c60-4abf-87ab-34b93184b67d.png">

**Comment by LiTaiChung** [comment]
他們應該也是用svg 

更新組件：components/NextLogo.tsx

**Comment by yuaanlin** [comment]
Closed in #27
