### ISSUE TITLE
Quiz 組件

### ISSUE THREAD

**Issue by yuaanlin** [yuaanlin/nextjs.tw#12]
在 `/learn` 路徑下有許多互動式的教學文章，其中「互動式」的關鍵是 Quiz 組件，如下圖範例：

<img width="725" alt="Screen Shot 2022-09-03 at 2 14 44 PM" src="https://user-images.githubusercontent.com/21105863/188258424-a2ca0a1d-3750-48fe-a648-98b104127764.png">

<img width="725" alt="Screen Shot 2022-09-03 at 2 15 24 PM" src="https://user-images.githubusercontent.com/21105863/188258442-89f7cfa5-3f24-40d4-bf45-d01e6f8c5c27.png">

<img width="724" alt="Screen Shot 2022-09-03 at 2 15 43 PM" src="https://user-images.githubusercontent.com/21105863/188258454-5bfe658f-d918-4991-bede-b39975e48022.png">

需要把這個 Quiz 做成一個 Component 然後讓 MDX 可以引用。

**Comment by rayatn1011** [comment]
這個我來完成！
-
I'll finish this!

**Comment by yuaanlin** [comment]
Closed in #52
