### ISSUE TITLE
`/learn` 頁面的左邊 Nav 導航欄

### ISSUE THREAD

**Issue by yuaanlin** [yuaanlin/nextjs.tw#29]
<img width="1717" alt="Screen Shot 2022-09-05 at 10 51 59 PM" src="https://user-images.githubusercontent.com/21105863/188475789-22ba7dbd-1bf1-4d85-bb9a-9e18cfb7d46c.png">

<img width="1717" alt="Screen Shot 2022-09-05 at 10 52 14 PM" src="https://user-images.githubusercontent.com/21105863/188475878-75836d84-ffb4-4df7-b278-42748ed85580.png">

**Comment by YONG-LIN-LIANG** [comment]
I got this!

**Comment by yuaanlin** [comment]
Closed in #38 , thanks for the contribution!
